### ISSUE TITLE
MetricServer.Stop still cause "ObjectDisposedException"

### ISSUE THREAD

**Issue by easyalgoltd** [andrasm/prometheus-net#16]
Hello.

I am still experiencing "ObjectDisposedException" on server stop.
Here is exception detail:

Cannot access a disposed object.
Object name: System.Net.HttpListener.

   at System.Net.HttpListener.CheckDisposed()
   at System.Net.HttpListener.BeginGetContext(AsyncCallback callback, Object state)
   at Prometheus.MetricServer.<StartLoop>b__6_0(Action repeatAction)
   at System.Reactive.Concurrency.Scheduler.<Schedule>b__45(Action`1 _action, Action`1 self)
   at System.Reactive.Concurrency.Scheduler.<>c__DisplayClass50`1.<InvokeRec1>b__4d(TState state1)
   at System.Reactive.Concurrency.Scheduler.<>c__DisplayClass50`1.<>c__DisplayClass52.<InvokeRec1>b__4f(IScheduler scheduler1, TState state3)
   at System.Reactive.Concurrency.DefaultScheduler.<>c__DisplayClass1`1.<Schedule>b__0(Object _)
   at System.Reactive.Concurrency.DefaultConcurrencyAbstractionLayer.<>c__DisplayClass1.<QueueUserWorkItem>b__0(Object _)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by andrasm** [comment]
thanks - managed to reproduce. didn't have time to diagnose in depth, but added exception handling so at least it won't bubble up. Pushed the new version (1.1.2) to nuget.
