### ISSUE TITLE
Building solution and running "tester" results in exception

### ISSUE THREAD

**Issue by sandersaares** [andrasm/prometheus-net#42]
I cloned the solution and ran the included "tester" utility but it apparently crashes due to missing protobuf-net assembly binding redirect.

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Prometheus.Advanced.Collector`1' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Prometheus.Internal.LabelValues' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'protobuf-net, Version=2.0.0.668, Culture=neutral, PublicKeyToken=257b51d87d2e4d67' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Prometheus.Internal.LabelValues..ctor(String[] names, String[] values)
   at Prometheus.Internal.LabelValues..cctor() in c:\Source\prometheus-net\prometheus-net.shared\Internal\LabelValues.cs:line 12
   --- End of inner exception stack trace ---
   at Prometheus.Internal.LabelValues..ctor(String[] names, String[] values)
   at Prometheus.Advanced.Collector`1..cctor() in c:\Source\prometheus-net\prometheus-net.shared\Advanced\Collector.cs:line 22
   --- End of inner exception stack trace ---
   at Prometheus.Advanced.Collector`1..ctor(String name, String help, String[] labelNames) in c:\Source\prometheus-net\prometheus-net.shared\Advanced\Collector.cs:line 54
   at Prometheus.Counter..ctor(String name, String help, String[] labelNames) in c:\Source\prometheus-net\prometheus-net.shared\Counter.cs:line 18
   at Prometheus.Advanced.MetricFactory.CreateCounter(String name, String help, String[] labelNames) in c:\Source\prometheus-net\prometheus-net.shared\Advanced\MetricFactory.cs:line 18
   at Prometheus.Metrics.CreateCounter(String name, String help, String[] labelNames) in c:\Source\prometheus-net\prometheus-net.shared\Metrics.cs:line 14
   at Prometheus.Advanced.DotNetStatsCollector.RegisterMetrics() in c:\Source\prometheus-net\prometheus-net.shared\Advanced\DotNetStatsCollector.cs:line 32
   at Prometheus.Advanced.DefaultCollectorRegistry.RegisterOnDemandCollectors(IEnumerable`1 onDemandCollectors) in c:\Source\prometheus-net\prometheus-net.shared\Advanced\DefaultCollectorRegistry.cs:line 21
   at Prometheus.MetricHandler..ctor(IEnumerable`1 standardCollectors, ICollectorRegistry registry) in c:\Source\prometheus-net\prometheus-net.shared\MetricHandler.cs:line 26
   at Prometheus.MetricServer..ctor(String hostname, Int32 port, IEnumerable`1 standardCollectors, String url, ICollectorRegistry registry, Boolean useHttps) in c:\Source\prometheus-net\prometheus-net.shared\MetricServer.cs:line 18
   at tester.MetricServerTester.InitializeMetricHandler() in c:\Source\prometheus-net\tester\MetricServerTester.cs:line 16
   at tester.Program.Main(String[] args) in c:\Source\prometheus-net\tester\Program.cs:line 17
```

**Comment by sandersaares** [comment]
In fact, it looks like tester uses `2.1.0` whereas all the libraries use `2.0.0.668`. Perhaps this inconsistency needs to be solved, as well.
