### ISSUE TITLE
Trying to create server on 0.0.0.0 throws exception

### ISSUE THREAD

**Issue by mzabani** [andrasm/prometheus-net#62]
**EDIT: This exception is wrong. See my next comment.**
I'm not sure if this is something I'm doing wrong, but I get an exception when trying to:

`var server = new MetricServer("0.0.0.0", 10000);
 server.Start();`

The exception is:
`System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListener'.
   at System.Net.HttpListener.CheckDisposed()
   at System.Net.HttpListener.Stop()
   at Prometheus.MetricServer.StopInner() in C:\MyData\dev\prometheus-net\prometheus-net.shared\MetricServer.cs:line 74
   at Prometheus.MetricHandler.Stop() in C:\MyData\dev\prometheus-net\prometheus-net.shared\MetricHandler.cs:line 38`

Is this something I'm doing wrong or is it a bug?

Thanks in advance,
Marcelo.

**Comment by mzabani** [comment]
Actually the exception above is wrong. The original exception is:

System.Net.HttpListenerException (0x80004005): The request is not supported
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Prometheus.MetricServer.StartLoop(IScheduler scheduler)
   at Prometheus.MetricHandler.Start(IScheduler scheduler)

Trying to listen on the "*" host gives me access denied instead (something typical of HttpListeners).

**Comment by sandersaares** [comment]
This is by design - that is just how HttpListener works. Do not use 0.0.0.0.

Use "*" or "+" if you want to listen on all addresses. To understand the "access denied" situation, the answers here may be illuminating: https://stackoverflow.com/questions/2583347/c-sharp-httplistener-without-using-netsh-to-register-a-uri
